### ISSUE TITLE
Clean install bug

### ISSUE THREAD

**Issue by RicardoUsbeck** [dbpedia/chatbot#18]
Hi,

using a virgin system environment I get the following error running git clone + mvn spring-boot:run. Maybe @yamalight has an idea?

[INFO] Node v4.3.0 is already installed.
[INFO] Installing npm version 5.3.0
[INFO] Downloading http://registry.npmjs.org/npm/-/npm-5.3.0.tgz to /Users/ricardousbeck/.m2/repository/com/github/eirslett/npm/5.3.0/npm-5.3.0.tar.gz
[INFO] No proxies configured
[INFO] No proxy was configured, downloading directly
[INFO] Unpacking /Users/ricardousbeck/.m2/repository/com/github/eirslett/npm/5.3.0/npm-5.3.0.tar.gz into /Users/ricardousbeck/workspace/chatbot/node/node_modules
[INFO] Installed npm locally.
[INFO] 
[INFO] --- frontend-maven-plugin:1.4:npm (npm-install-modules) @ dbpedia-chabot ---
[INFO] Running 'npm install --unsafe-perm' in /Users/ricardousbeck/workspace/chatbot
[INFO] 
[INFO] > fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.1.1.tgz install /Users/ricardousbeck/workspace/chatbot/node_modules/fsevents
[INFO] > node install
[INFO] 
[ERROR] node-pre-gyp info it worked if it ends with ok
[ERROR] node-pre-gyp verb cli [ '/Users/ricardousbeck/workspace/chatbot/node/node',
[ERROR] node-pre-gyp verb cli   '/Users/ricardousbeck/workspace/chatbot/node_modules/fsevents/node_modules/.bin/node-pre-gyp',
[ERROR] node-pre-gyp verb cli   'install',
[ERROR] node-pre-gyp verb cli   '--fallback-to-build' ]
[ERROR] node-pre-gyp info using node-pre-gyp@https://registry.npmjs.org/node-pre-gyp/-/node-pre-gyp-0.6.33.tgz
[ERROR] node-pre-gyp info using node@4.3.0 | darwin | x64
[ERROR] node-pre-gyp verb command install []
[ERROR] node-pre-gyp ERR! install error 
[ERROR] node-pre-gyp ERR! stack TypeError: Cannot read property 'version' of null
[ERROR] node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/Users/ricardousbeck/workspace/chatbot/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:270:32)
[ERROR] node-pre-gyp ERR! stack     at install (/Users/ricardousbeck/workspace/chatbot/node_modules/fsevents/node_modules/node-pre-gyp/lib/install.js:168:31)
[ERROR] node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/Users/ricardousbeck/workspace/chatbot/node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js:50:37)
[ERROR] node-pre-gyp ERR! stack     at run (/Users/ricardousbeck/workspace/chatbot/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
[ERROR] node-pre-gyp ERR! stack     at Object.<anonymous> (/Users/ricardousbeck/workspace/chatbot/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
[ERROR] node-pre-gyp ERR! stack     at Module._compile (module.js:410:26)
[ERROR] node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:417:10)
[ERROR] node-pre-gyp ERR! stack     at Module.load (module.js:344:32)
[ERROR] node-pre-gyp ERR! stack     at Function.Module._load (module.js:301:12)
[ERROR] node-pre-gyp ERR! stack     at Function.Module.runMain (module.js:442:10)
[ERROR] node-pre-gyp ERR! System Darwin 16.7.0
[ERROR] node-pre-gyp ERR! command "/Users/ricardousbeck/workspace/chatbot/node/node" "/Users/ricardousbeck/workspace/chatbot/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
[ERROR] node-pre-gyp ERR! cwd /Users/ricardousbeck/workspace/chatbot/node_modules/fsevents
[ERROR] node-pre-gyp ERR! node -v v4.3.0
[ERROR] node-pre-gyp ERR! node-pre-gyp -v vhttps://registry.npmjs.org/node-pre-gyp/-/node-pre-gyp-0.6.33.tgz
[ERROR] node-pre-gyp ERR! not ok 
[INFO] Cannot read property 'version' of null
[INFO] 
[INFO] > dbpedia-chatbot@0.0.1 postinstall /Users/ricardousbeck/workspace/chatbot
[INFO] > ./node/node ./node_modules/.bin/webpack -p
[INFO] 
[INFO] Hash: 32d978d77937a81c9fbd
[INFO] Version: webpack 2.5.1
[INFO] Time: 17687ms
[INFO]       Asset    Size  Chunks                    Chunk Names
[INFO]    admin.js  392 kB       0  [emitted]  [big]  admin
[INFO]    embed.js  388 kB       1  [emitted]  [big]  embed
[INFO]      app.js  291 kB       2  [emitted]  [big]  app
[INFO] feedback.js  264 kB       3  [emitted]  [big]  feedback
[INFO]    login.js  101 kB       4  [emitted]         login
[INFO]    [9] ./~/react/react.js 56 bytes {0} {1} {2} {3} [built]
[INFO]   [16] ./~/react/lib/React.js 3.32 kB {0} {1} {2} {3} [built]
[INFO]   [49] ./~/react-dom/index.js 59 bytes {0} {1} {2} {3} [built]
[INFO]   [82] ./~/style-loader/addStyles.js 9.15 kB {0} {1} {2} {3} {4} [built]
[INFO]   [85] ./app/src/less/pages/app.less 1.18 kB {0} {1} {2} [built]
[INFO]  [197] ./app/src/less/pages/admin.less 1.18 kB {0} [built]
[INFO]  [198] ./app/src/less/pages/embed.less 1.18 kB {1} [built]
[INFO]  [199] ./app/src/less/pages/feedback.less 1.19 kB {3} [built]
[INFO]  [200] ./app/src/less/pages/login.less 1.18 kB {4} [built]
[INFO]  [201] ./app/src/js/admin.js 582 bytes {0} [built]
[INFO]  [203] ./app/src/js/embed.js 582 bytes {1} [built]
[INFO]  [204] ./app/src/js/feedback.js 579 bytes {3} [built]
[INFO]  [205] ./app/src/js/index.js 553 bytes {2} [built]
[INFO]  [206] ./app/src/js/login.js 51 bytes {4} [built]
[INFO]  [207] ./~/css-loader!./~/less-loader/dist/cjs.js!./app/src/less/pages/admin.less 94.7 kB {0} [built]
[INFO]     + 196 hidden modules
[WARNING] npm WARN dbpedia-chatbot@0.0.1 No license field.
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.1.1.tgz (node_modules/fsevents):
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@https://registry.npmjs.org/fsevents/-/fsevents-1.1.1.tgz install: `node install`
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
[ERROR] 
[INFO] added 675 packages and removed 1391 packages in 242.019s
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ dbpedia-chabot ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 35 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ dbpedia-chabot ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 69 source files to /Users/ricardousbeck/workspace/chatbot/target/classes
[WARNING] /Users/ricardousbeck/workspace/chatbot/src/main/java/codeanticode/eliza/ElizaMain.java: /Users/ricardousbeck/workspace/chatbot/src/main/java/codeanticode/eliza/ElizaMain.java uses or overrides a deprecated API.
[WARNING] /Users/ricardousbeck/workspace/chatbot/src/main/java/codeanticode/eliza/ElizaMain.java: Recompile with -Xlint:deprecation for details.
[WARNING] /Users/ricardousbeck/workspace/chatbot/src/main/java/codeanticode/eliza/KeyList.java: Some input files use unchecked or unsafe operations.
[WARNING] /Users/ricardousbeck/workspace/chatbot/src/main/java/codeanticode/eliza/KeyList.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ dbpedia-chabot ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/ricardousbeck/workspace/chatbot/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ dbpedia-chabot ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 19 source files to /Users/ricardousbeck/workspace/chatbot/target/test-classes
[INFO] 
[INFO] <<< spring-boot-maven-plugin:1.5.2.RELEASE:run (default-cli) < test-compile @ dbpedia-chabot <<<
[INFO] 
[INFO] --- spring-boot-maven-plugin:1.5.2.RELEASE:run (default-cli) @ dbpedia-chabot ---
[INFO] Attaching agents: []
20:46:07.194 [main] DEBUG org.springframework.boot.devtools.settings.DevToolsSettings - Included patterns for restart : []
20:46:07.197 [main] DEBUG org.springframework.boot.devtools.settings.DevToolsSettings - Excluded patterns for restart : [/spring-boot-starter/target/classes/, /spring-boot-autoconfigure/target/classes/, /spring-boot-starter-[\w-]+/, /spring-boot/target/classes/, /spring-boot-actuator/target/classes/, /spring-boot-devtools/target/classes/]
20:46:07.198 [main] DEBUG org.springframework.boot.devtools.restart.ChangeableUrls - Matching URLs for reloading : [file:/Users/ricardousbeck/workspace/chatbot/target/classes/]

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.2.RELEASE)

2017-08-18 20:46:07.599  INFO 21151 --- [  restartedMain] chatbot.Application                      : Starting Application on MacBook-Pro with PID 21151 (/Users/ricardousbeck/workspace/chatbot/target/classes started by ricardousbeck in /Users/ricardousbeck/workspace/chatbot)
2017-08-18 20:46:07.600  INFO 21151 --- [  restartedMain] chatbot.Application                      : No active profile set, falling back to default profiles: default
2017-08-18 20:46:07.917  INFO 21151 --- [  restartedMain] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@21659597: startup date [Fri Aug 18 20:46:07 CEST 2017]; root of context hierarchy
2017-08-18 20:46:09.279  INFO 21151 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cache.annotation.ProxyCachingConfiguration' of type [org.springframework.cache.annotation.ProxyCachingConfiguration$$EnhancerBySpringCGLIB$$aa7d6810] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-08-18 20:46:09.307  INFO 21151 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration' of type [org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration$$EnhancerBySpringCGLIB$$9ef12cb4] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-08-18 20:46:09.331  INFO 21151 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'spring.cache-org.springframework.boot.autoconfigure.cache.CacheProperties' of type [org.springframework.boot.autoconfigure.cache.CacheProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-08-18 20:46:09.340  INFO 21151 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'cacheManagerCustomizers' of type [org.springframework.boot.autoconfigure.cache.CacheManagerCustomizers] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-08-18 20:46:09.346  INFO 21151 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.autoconfigure.cache.GuavaCacheConfiguration' of type [org.springframework.boot.autoconfigure.cache.GuavaCacheConfiguration$$EnhancerBySpringCGLIB$$f68e6551] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-08-18 20:46:09.376  INFO 21151 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'cacheManager' of type [org.springframework.cache.guava.GuavaCacheManager] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-08-18 20:46:09.377  INFO 21151 --- [  restartedMain] trationDelegate$BeanPostProcessorChecker : Bean 'cacheAutoConfigurationValidator' of type [org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration$CacheManagerValidator] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-08-18 20:46:09.706  INFO 21151 --- [  restartedMain] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)
2017-08-18 20:46:09.722  INFO 21151 --- [  restartedMain] o.apache.catalina.core.StandardService   : Starting service Tomcat
2017-08-18 20:46:09.723  INFO 21151 --- [  restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.11
2017-08-18 20:46:09.828  INFO 21151 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2017-08-18 20:46:09.829  INFO 21151 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1915 ms
2017-08-18 20:46:09.989  INFO 21151 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2017-08-18 20:46:09.989  INFO 21151 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2017-08-18 20:46:09.989  INFO 21151 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2017-08-18 20:46:09.989  INFO 21151 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2017-08-18 20:46:09.990  INFO 21151 --- [ost-startStop-1] .s.DelegatingFilterProxyRegistrationBean : Mapping filter: 'springSecurityFilterChain' to: [/*]
2017-08-18 20:46:10.014  INFO 21151 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'dispatcherServlet' to [/]
2017-08-18 20:46:10.140 ERROR 21151 --- [  restartedMain] c.c.c.spring.CloudantAutoConfiguration   : Can not initiate Cloudant client from Spring config.
2017-08-18 20:46:10.141  WARN 21151 --- [  restartedMain] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'application.Helper' defined in file [/Users/ricardousbeck/workspace/chatbot/target/classes/chatbot/Application$Helper.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cloudantClient' defined in class path resource [com/clianz/cloudant/spring/CloudantAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.cloudant.client.api.CloudantClient]: Factory method 'cloudantClient' threw exception; nested exception is java.lang.RuntimeException: No valid configuration for Cloudant client found.
2017-08-18 20:46:10.166  INFO 21151 --- [  restartedMain] o.apache.catalina.core.StandardService   : Stopping service Tomcat
2017-08-18 20:46:10.185  WARN 21151 --- [  restartedMain] o.s.boot.SpringApplication               : Error handling failed (Error creating bean with name 'delegatingApplicationListener' defined in org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.annotation.ProxyCachingConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' available)
2017-08-18 20:46:10.192 ERROR 21151 --- [  restartedMain] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'application.Helper' defined in file [/Users/ricardousbeck/workspace/chatbot/target/classes/chatbot/Application$Helper.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cloudantClient' defined in class path resource [com/clianz/cloudant/spring/CloudantAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.cloudant.client.api.CloudantClient]: Factory method 'cloudantClient' threw exception; nested exception is java.lang.RuntimeException: No valid configuration for Cloudant client found.
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:189) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1193) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1095) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at chatbot.Application.main(Application.java:170) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-1.5.2.RELEASE.jar:1.5.2.RELEASE]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cloudantClient' defined in class path resource [com/clianz/cloudant/spring/CloudantAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.cloudant.client.api.CloudantClient]: Factory method 'cloudantClient' threw exception; nested exception is java.lang.RuntimeException: No valid configuration for Cloudant client found.
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	... 24 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.cloudant.client.api.CloudantClient]: Factory method 'cloudantClient' threw exception; nested exception is java.lang.RuntimeException: No valid configuration for Cloudant client found.
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	... 37 common frames omitted
Caused by: java.lang.RuntimeException: No valid configuration for Cloudant client found.
	at com.clianz.cloudant.spring.CloudantAutoConfiguration.createCloudantClient(CloudantAutoConfiguration.java:82) ~[cloudant-spring-boot-starter-0.9.5.jar:na]
	at com.clianz.cloudant.spring.CloudantAutoConfiguration.cloudantClient(CloudantAutoConfiguration.java:38) ~[cloudant-spring-boot-starter-0.9.5.jar:na]
	at com.clianz.cloudant.spring.CloudantAutoConfiguration$$EnhancerBySpringCGLIB$$8e9d71f3.CGLIB$cloudantClient$3(<generated>) ~[cloudant-spring-boot-starter-0.9.5.jar:na]
	at com.clianz.cloudant.spring.CloudantAutoConfiguration$$EnhancerBySpringCGLIB$$8e9d71f3$$FastClassBySpringCGLIB$$82114abc.invoke(<generated>) ~[cloudant-spring-boot-starter-0.9.5.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) ~[spring-context-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at com.clianz.cloudant.spring.CloudantAutoConfiguration$$EnhancerBySpringCGLIB$$8e9d71f3.cloudantClient(<generated>) ~[cloudant-spring-boot-starter-0.9.5.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	... 38 common frames omitted

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11:51 min
[INFO] Finished at: 2017-08-18T20:46:10+02:00
[INFO] Final Memory: 39M/221M
[INFO] ------------------------------------------------------------------------

**Comment by RicardoUsbeck** [comment]
UPDATE: After adding src/main/resource/application.properties with the config provided at README.md the Node-related error does not occur anymore but "the Factory method 'cloudantClient' threw exception; nested exception is java.net.MalformedURLException: no protocol:" still exists. We should catch this exception and just do not do anything with the db if it is not present. I am thinking, maybe this is worth an issue on its own.

**Comment by yamalight** [comment]
Aside from that missing prop, that definitely looks like java-related error to me.

**Comment by ram-g-athreya** [comment]
Hi @RicardoUsbeck 

The problem with catching that is that the error occurs in Autoload of the Cloudant library. 

A valid DB configuration is necessary for Cloudant to run. I am looking into it but do you have any ideas if there is a way to catch that?

Thanks
Ram G Athreya

**Comment by ram-g-athreya** [comment]
Hi @RicardoUsbeck 

I have added some try catch scenarios in the code now and updated the README with a GitHub Gist Link to a dummy configuration file in the develop branch. Please read the environment configuration section in the README where I have added these.

Could you please check out the develop branch and run the app with the dummy configuration.

Thanks
Ram G Athreya

**Comment by RicardoUsbeck** [comment]
The bug fix works fine. Let's merge the READMe file and directly paste the gist dummy config to the wiki so the project is not depending on your account :)

**Comment by ram-g-athreya** [comment]
Ok
